[tool.black]
line-length = 88
target-version = ['py310']
exclude = '''
    /(venv|\.git|__pycache__)/
'''

[tool.ruff]
select = ["E", "F", "B"]
ignore = ["E501"]
unfixable = ["B"]

[tool.ruff.lint.per-file-ignores]
# Ignore `F401` and `F821` in `main.py`.
"main.py" = ["F401", "F821"]
