name: Deployment

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Clone repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Create the SSH private key file
      - name: Make key file
        run: |
          touch vapi-vm2-reedi-backend
          chmod 600 vapi-vm2-reedi-backend
          echo "${{ secrets.VM_KEY }}" > vapi-vm2-reedi-backend
          
      # Create the .ssh directory
      - name: Create .ssh directory
        run: |
          mkdir -p ~/.ssh
          
      # List files for debugging
      - name: List files
        run: ls -la

      # Add the server to known hosts
      - name: Add server to known hosts
        run: |
          ssh-keyscan -H 20.193.149.51 >> ~/.ssh/known_hosts

      # Establish connection and create directory
      - name: Establish connection
        run: |
          ssh -i vapi-vm2-reedi-backend -o StrictHostKeyChecking=no abodoo@20.193.149.51 << 'EOF'
          mkdir -p api2
          EOF

     
