name: Deployment

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Clone repository
      - name: Checkout code
        uses: actions/checkout@v2
      # Setup python and dependencies
      - name: establish connection
        run: | 
          ssh -i vapi-vm2-reedi-backend abodoo@20.193.149.51 <<
          mkdir api2
          EOF
     
