name: Python CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Specify the Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Check formatting with black
      run: |
        black --check .

    - name: Lint with ruff
      run: |
        ruff check .
